#!/bin/bash

modprobe vfio-pci

for dev in "$@"; do
        vendor=$(cat /sys/bus/pci/devices/$dev/vendor)
        device=$(cat /sys/bus/pci/devices/$dev/device)
        if [ -e /sys/bus/pci/devices/$dev/driver ]; then
                echo $dev > sudo tee /sys/bus/pci/devices/$dev/driver/unbind
        fi
        sudo echo $vendor $device > sudo tee /sys/bus/pci/drivers/vfio-pci/new_id
done
